baseURL = "https://tilburgsciencehub.com"
languageCode = "en-us"
title = "Tilburg Science Hub"
theme = "tilburg"
pygmentsUseClasses=true
enableInlineShortcodes = true

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
  repo_url="https://github.com/tilburgsciencehub/website"

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[taxonomies]
third_level = "third_levels"
