version: "3.8"
services:
  frontend:
    build: .
    command: sh -exc "exec env gunicorn app:app --bind 0.0.0.0:8000 --workers 4"
    ports:
      - 8070:8000
    tty: true
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.http.routers.frontend.rule=Host(`tilburgsciencehub.com`)"
